source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

def curl
  pod 'SwiftyCurl', :path => '../'
end

target 'SwiftyCurl_Example' do
  platform :ios, '12.0'

  curl

  target 'SwiftyCurl_Tests' do
    inherit! :search_paths
  end
end

target 'macOS_Example' do
  platform :macos, '12.0'

  curl
end
